export default [
    {title: "CODE-CWA", subtitle: "Organizer", dates: "October 2022 - present"},
    {title: "ControlZee", subtitle: "Senior Software Engineer", dates: "March 2022 - present"},
    {title: "The Solidarity Fund by Coworker", subtitle: "Committee Member", dates: "October 2021 - present"},
    {title: "Apple", subtitle: "Principal Software Engineer", dates: "April 2020 - November 2021"},
    {title: "Webflow", subtitle: "Senior Software Engineer", dates: "April 2019 - April 2020"},
    {title: "University of Washington", subtitle: "Instructor", dates: "January 2018 - May 2018"},
    {title: "Starbucks", subtitle: "Lead Software Engineer", dates: "November 2017 - April 2019"},
    {title: "World Wide Technology", subtitle: "Senior Software Engineer", dates: "September 2016 - August 2017"},
    {title: "Orange County Probation: OC Grip", subtitle: "Mentor", dates: "August 2015 - August 2016"},
    {title: "Blizzard Entertainment", subtitle: "Software Engineer", dates: "August 2015 - August 2016"},
    {title: "USA Today", subtitle: "Senior Developer, Web & Emerging Platforms", dates: "November 2011 - August 2015"},
    {title: "Operation Food Search", subtitle: "Social Media Coordinator", dates: "January 2011 - October 2011"},
    {title: "Rules Based Medicine", subtitle: "Research Associate", dates: "January 2009 - June 2009"},
    {title: "Neutrino", subtitle: "Front-End Developer", dates: "January 2008 - November 2011"},
    {title: "LuxuryRealEstate.com", subtitle: "Web Developer", dates: "May 2007 - January 2008"},
]